- name: Check for Miniconda installation
  stat: path=/opt/anaconda/bin/conda
  changed_when: false
  register: conda_binary

- name: Install Anaconda
  when: not conda_binary.stat.exists
  shell: |
      cp {{ ansible_env.ANSIBLE_INSTALL_SOURCE_DIR }}/Miniconda3-latest-Linux-x86_64.sh /tmp/miniconda.sh
      cd /tmp
      bash miniconda.sh -b -f -p /opt/anaconda
      rm -f miniconda.sh

- name: Check for condarc file
  stat: path=/opt/anaconda/.condarc
  changed_when:  false
  register: conda_rc

- name: Configure Anaconda
  when: not conda_rc.stat.exists
  copy: src=files/condarc.vault dest=/opt/anaconda/.condarc  owner=root group=root mode=0644
