---
# IPFS installation:
- name: Check for IPFS installation
  stat: path=/usr/lib/go-ipfs
  changed_when: false
  register: ipfs_install

- name: Check for supervisord installation
  stat: path=/etc/supervisord.conf
  changed_when: false
  register: supervisord_install

- name: Install Supervisor Package for IPFS
  when: not supervisord_install.stat.exists
  yum:
    name:
      - supervisor
    state: installed

- name: append to supervisord configuration file
  blockinfile:
    path: /etc/supervisord.conf
    block: "{{ lookup('file', 'files/etc/supervisord.conf') }}"

- name: Adding IPFS node
  shell: |
    tar -xvf {{ ansible_env.ANSIBLE_INSTALL_SOURCE_DIR }}/go-ipfs_v0.4.18_linux-amd64.tar.gz -C /usr/lib/
    chown -R root:root /usr/lib/go-ipfs/
    chmod -R 775 /usr/lib/go-ipfs/
    ln -s /usr/lib/go-ipfs/ipfs /usr/bin/ipfs
    ipfs init
    chown -R root:root ~/.ipfs
    chmod -R 775 ~/.ipfs
    mkdir /ipfs
    chmod 777 /ipfs
    systemctl enable supervisord
    systemctl restart supervisord
